### ISSUE TITLE
windows doc yupdate

### ISSUE THREAD

**Issue by dridk** [mherrmann/fbs-tutorial#31]
On a fresh installation of windows 7 on virtual box, I did 2 things more not explained in your tutorial. 

```
fbs freeze 
==> ImportError: No module named win32com.client
pip install pypiwin32    

fbs freeze  
===> MSVCR100.dll is missing, Install Visual C++ Visual Studio 2012
https://www.microsoft.com/en-us/download/confirmation.aspx?id=30679    

fbs freeze  
===> Works ! 
```

**Comment by mherrmann** [comment]
Thank you for letting me know. I feel the first (`win32com.client`) is unique to your setup, because fbs has no dependency on this module. The second one (`msvcr100.dll`) is a "feature" of fbs, and I feel the explanation it offers is so clear that I don't need to separately mention it in the tutorial.

But either way, your post here is helpful, because other people may find it through Google. So, for that and the suggestion in general, thank you.
