### ISSUE TITLE
pyside6

### ISSUE THREAD

**Issue by ashwin31** [mherrmann/fbs-tutorial#59]
can you provide pyside6 sample app like what is there avaialbel for pyqt5

**Comment by mherrmann** [comment]
I'm afraid I can't because the tutorial uses the free version of fbs, which only supports PyQt5 and PySide2. Using PySide6 requires [fbs Pro](https://build-system.fman.io/pro). However, once you have Pro, you can follow the same steps as are described in the tutorial by simply replacing "PyQt5" by "PySide6".

**Comment by ashwin31** [comment]
Thank you. It worked.
